workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Run tests
        script: flutter test
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
