workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: 3.10.0  # Reemplaza con la versión más reciente de Flutter compatible con Dart >= 3.7.0
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Run tests
        script: flutter test
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
