workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: stable # Alternatively, specify a specific version like "3.13.0"
    scripts:
      - name: Install dependencies
        script: |
          flutter --version
          flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
