workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: stable
    scripts:
      # Instala las dependencias de Flutter
      - name: Install dependencies
        script: |
          flutter pub get
      # Ejecuta los tests
      - name: Run tests
        script: |
          flutter test
      # Construye la aplicación para Android y iOS
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      # Define los artefactos a generar y publicar
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
